services:
    db:
        image: postgres:14.5
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: medicalData
        ports: 
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./postgres/init:/docker-entrypoint-initdb.d
            - ./postgres/data:/data
        networks:
            - bdt_network
        restart: always

    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - bdt_network
        restart: always

    kafka:
        image: confluentinc/cp-kafka:7.6.0
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - ALLOW_PLAINTEXT_LISTENER=yes
        networks:
            - bdt_network
        restart: always

    spark:
        build: ./spark
        depends_on:
            - kafka
        volumes:
            - ./spark:/spark
            - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
        command: >
                bash -c "sleep 10 &&
                /opt/bitnami/spark/bin/spark-submit
                --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
                /spark/spark_stream.py"
        networks:
            - bdt_network
        restart: always

    flask_web:
        build: ./flask_app
        ports:
            - "8000:8000"
        volumes:
            - ./flask_app:/app
        depends_on:
            - kafka
            - db
        environment:
            - DB_HOST=db
            - DB_NAME=medicalData
            - DB_USER=user
            - DB_PASSWORD=password
            - KAFKA_BROKER=kafka:9092
        networks:
            - bdt_network
        restart: always
    data_generator:
        build: ./kafka
        command: python data_generator.py
        depends_on:
            - kafka
            - db
        volumes:
            - ./kafka:/app
        networks:
            - bdt_network
    dbstream:
        build:
            context: ./kafka
        depends_on:
            - kafka
        command: python db_to_kafka_stream.py
        volumes:
            - ./postgres/data:/app/data
        networks:
            - bdt_network

volumes:
    pgdata:

networks:
    bdt_network: