version: '3.8'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka:
        image: confluentinc/cp-kafka:7.4.0
        ports:
        - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    spark:
        image: bitnami/spark:latest
        depends_on:
        - kafka
        volumes:
        - ./spark:/spark
        - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
        command: bash -c "sleep 10 && python3 /spark/spark-stream.py"

    injector:
        image: python:3.10-slim
        depends_on:
            - kafka
        volumes:
            - ./kafka:/app
            - ./data:/data/csv/smart_home_sensor
        working_dir: /app
        command: bash -c "pip install -r requirements.txt && python3 injection.py"