# docker-compose file to build docker enviroment
services:
    db:
        image: postgres:14.5
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: medicalData
        ports: 
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./postgres/init:/docker-entrypoint-initdb.d
        networks:
            - bdt_network
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user"]
            interval: 5s
            timeout: 5s
            retries: 10

    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - bdt_network
        restart: always

    kafka:
        image: confluentinc/cp-kafka:7.6.0
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - ALLOW_PLAINTEXT_LISTENER=yes
        healthcheck:
            test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
            interval: 5s
            timeout: 5s
            retries: 10
        networks:
            - bdt_network
        restart: always

    flask_web:
        build: ./flask_app
        ports:
            - "8000:8000"
        volumes:
            - ./flask_app:/app
        depends_on:
            kafka:
                condition: service_healthy
            db:
                condition: service_healthy
            train_model:
                condition: service_completed_successfully
        environment:
            - DB_HOST=db
            - DB_NAME=medicalData
            - DB_USER=user
            - DB_PASSWORD=password
            - KAFKA_BROKER=kafka:9092
        networks:
            - bdt_network
        restart: always

    data_generator:
        build: 
            context: ./kafka
        command: python smart_data_producer.py
        depends_on:
            kafka:
                condition: service_healthy
            db:
                condition: service_healthy
            train_model:
                condition: service_completed_successfully
        environment:
            - DB_HOST=db
            - DB_NAME=medicalData
            - DB_USER=user
            - DB_PASSWORD=password
            - KAFKA_BROKER=kafka:9092
        volumes:
            - ./kafka:/app
        networks:
            - bdt_network
    
    train_model:
        build:
            context: ./ml_model
        depends_on:
            db:
                condition: service_healthy
            synthea-init:
                condition: service_completed_successfully
        environment:
            - DB_HOST=db
            - DB_NAME=medicalData
            - DB_USER=user
            - DB_PASSWORD=password
            - KAFKA_BROKER=kafka:9092
            - PYTHONUNBUFFERED=1
        volumes:
            - ./ml_model:/app
            - ./ml_model/output:/app/output
            - ./shared_modules:/shared
        networks:
            - bdt_network

    trainer_loop:
        build:
            context: ./ml_model
        command: python ml_model/train_loop.py
        depends_on:
            db:
                condition: service_healthy
            train_model:
                condition: service_completed_successfully
        volumes:
            - ./ml_model:/app
            - ./ml_model/output:/app/output
            - ./shared_modules:/shared
        networks:
            - bdt_network

    alert_producer:
        build:
            context: ./kafka
        command: python risk_level_producer.py
        depends_on:
            kafka:
                condition: service_healthy
            db:
                condition: service_healthy
            train_model:
                condition: service_completed_successfully
        environment:
            - DB_HOST=db
            - DB_NAME=medicalData
            - DB_USER=user
            - DB_PASSWORD=password
            - KAFKA_BROKER=kafka:9092
        volumes:
            - ./kafka:/app
        networks:
            - bdt_network
        restart: always

    synthea-init:
        build:
            context: ./postgres
        depends_on:
            db:
                condition: service_healthy
        environment:
            - DB_HOST=db
            - DB_NAME=medicalData
            - DB_USER=user
            - DB_PASSWORD=password
            - INITIAL_PATIENTS=100
        command: python initial_population.py
        networks:
            - bdt_network
        restart: "no"

    synthea-incremental-loader:
        build:
            context: ./postgres
        depends_on:
            db:
                condition: service_healthy
            synthea-init:
                condition: service_completed_successfully
        environment:
            - DB_HOST=db
            - DB_NAME=medicalData
            - DB_USER=user
            - DB_PASSWORD=password
            - GENERATE_INTERVAL=300 # every five minutes
            - DELAY_STARTUP=true
        command: python incremental_patient_loader.py
        networks:
            - bdt_network
        volumes:
            - ./shared_modules:/shared

volumes:
    pgdata:

networks:
    bdt_network: