version: '3.8'

services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"  # Adjust host port if needed (e.g., "5431:5432")
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/data

volumes:
  pgdata: