BEGIN;

-- Create tables

CREATE TABLE IF NOT EXISTS PATIENTS (
    ID UUID PRIMARY KEY,
    BIRTHDATE DATE NOT NULL,
    DEATHDATE DATE,
    SSN VARCHAR NOT NULL,
    DRIVERS VARCHAR,
    PASSPORT VARCHAR,
    PREFIX VARCHAR,
    FIRST VARCHAR NOT NULL,
    MIDDLE VARCHAR,
    LAST VARCHAR NOT NULL,
    SUFFIX VARCHAR,
    MAIDEN VARCHAR,
    MARITAL VARCHAR,
    RACE VARCHAR NOT NULL,
    ETHNICITY VARCHAR NOT NULL,
    GENDER VARCHAR NOT NULL,
    BIRTHPLACE VARCHAR NOT NULL,
    ADDRESS VARCHAR NOT NULL,
    CITY VARCHAR NOT NULL,
    STATE VARCHAR NOT NULL,
    COUNTY VARCHAR,
    FIPS VARCHAR,
    ZIP VARCHAR,
    LAT NUMERIC,
    LON NUMERIC,
    HEALTHCARE_EXPENSES NUMERIC NOT NULL,
    HEALTHCARE_COVERAGE NUMERIC NOT NULL,
    INCOME NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS CONDITIONS (
    START DATE NOT NULL,
    STOP DATE,
    PATIENT UUID NOT NULL REFERENCES PATIENTS(ID),
    ENCOUNTER UUID NOT NULL,
    SYSTEM VARCHAR NOT NULL,
    CODE VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS OBSERVATIONS (
    DATE TIMESTAMP NOT NULL,
    PATIENT UUID NOT NULL REFERENCES PATIENTS(ID),
    ENCOUNTER UUID,
    CATEGORY VARCHAR,
    CODE VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    VALUE VARCHAR NOT NULL,
    UNITS VARCHAR,
    TYPE VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS alerts (
    id SERIAL PRIMARY KEY,
    patient_id UUID REFERENCES patients(id) ON DELETE CASCADE,
    alert_type TEXT NOT NULL,
    room TEXT,
    message TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ecg (
    id SERIAL PRIMARY KEY,
    patient_id UUID REFERENCES patients(id),
    timestamp TIMESTAMP NOT NULL,
    lead TEXT NOT NULL,
    voltage DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS vital_signs (
    patient_id UUID REFERENCES patients(id),
    date TIMESTAMP,
    hr FLOAT,
    rr FLOAT,
    body_temperature FLOAT,
    spo2 FLOAT,
    gsr FLOAT,
    risk_level FLOAT,
    PRIMARY KEY (patient_id, date)
);

COMMIT;